In [12]:
import numpy as np
from numpy import array
from numpy import trace

x = array([
    [2],
    [6]
])

y = array([
    [1],
    [0],
])

X = array([
    [7, 5],
    [3, 6]
])

Y = array([
    [2,4],
    [1,0]
])

xxT = x.dot(x.T)
xyT = x.dot(y.T)
innerXX = trace(xxT)
innerXY = trace(xyT)

print(innerXX + innerXY)



42


In [6]:
print(x.dot(y.T))

[[2 0]
 [6 0]]


In [10]:
print(X * Y)

[[14 20]
 [ 3  0]]


In [13]:
print(2 * X + 2*Y + X.T.dot(Y))

[[35 46]
 [24 32]]
