In [51]:
import numpy as np
from numpy import genfromtxt 
from numpy import trace

A = genfromtxt('../data/test_A.csv', delimiter=',')
B = genfromtxt('../data/test_B.csv', delimiter=',')
C = genfromtxt('../data/test_C.csv', delimiter=',')
x = genfromtxt('../data/test_x.csv', delimiter=',')
y = genfromtxt('../data/test_y.csv', delimiter=',')
z = genfromtxt('../data/test_z.csv', delimiter=',')

x = np.reshape(x, (5,1))
y = np.reshape(y, (5,1))
z = np.reshape(z, (3,1))

print(f'1. <A,A> = {trace(np.dot(A,A.T))}')
print(f'2. A hadamard B = \n{A * B}')
print(f'3. Tr(x outer y) = {trace(np.dot(x,y.T))}')
print(f'4. ABT = \n{np.dot(A, B.T)}')
print(f'5. ABTCx = \n {np.dot(np.dot(np.dot(A, B.T), C), x) }')
print(f'6. C(x + y) = \n{np.dot(C, x + y)}')
print(f'7. ||x||0 = {np.count_nonzero(x)}, ||x||1 = {np.linalg.norm(x, 1)}')


1. <A,A> = 25.0
2. A hadamard B = 
[[0. 2. 2.]
 [2. 2. 0.]
 [2. 4. 0.]
 [2. 0. 0.]
 [0. 4. 1.]
 [0. 0. 0.]]
3. Tr(x outer y) = 2.0
4. ABT = 
[[4. 6. 2. 2. 4. 3.]
 [2. 4. 6. 6. 2. 1.]
 [6. 9. 6. 6. 6. 4.]
 [0. 1. 2. 2. 0. 0.]
 [5. 6. 4. 4. 5. 3.]
 [0. 0. 0. 0. 0. 0.]]
5. ABTCx = 
 [[ 62.]
 [ 82.]
 [122.]
 [ 22.]
 [ 88.]
 [  0.]]
6. C(x + y) = 
[[ 7.]
 [ 8.]
 [14.]
 [ 9.]
 [ 7.]
 [ 9.]]
7. ||x||0 = 2, ||x||1 = 3.0
